# Soliguide: Useful information for those who need it
#
# SPDX-FileCopyrightText: Â© 2024 Solinum
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: _Manage Clever Cloud instances

on:
  workflow_dispatch:
    inputs:
      action:
        description: the action to perform on the instance (start or stop)
        type: choice
        options:
          - restart
          - stop
      environment_prefix:
        description: the environment prefix of Clever Cloud applications aliases in .clever.json
        required: true
        type: choice
        options:
          - DEMO
          - TEST1
          - TEST2
  workflow_call:
    inputs:
      action:
        description: The action to perform on the instance (start or stop)
        type: string
      environment_prefix:
        description: The environment prefix of Clever Cloud applications aliases in .clever.json
        required: true
        type: string
    secrets:
      CLEVER_TOKEN:
        description: Clever CLI token
        required: true
      CLEVER_SECRET:
        description: Clever CLI secret
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment_prefix }}-${{ inputs.action }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  do-clever-cloud-action-on-instance:
    name: Do Clever Cloud action on instance
    runs-on: ubuntu-latest
    container:
      image: clevercloud/clever-tools:3.7.0
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Do ${{ inputs.action }} on all applications of environment ${{ inputs.environment_prefix }}
        run: clever applications --only-aliases | grep ${{ inputs.environment_prefix }} | xargs -I % clever ${{ inputs.action }} --alias %
